name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet pacakges
      run: msbuild src\Experiment1.slnx -t:restore

    - name: Build app for release
      run: msbuild src\Experiment1.slnx -t:build -property:Configuration=Release
  
    - name: Upload setup artifact
      uses: actions/upload-artifact@v4
      with:
        name: setup
        path: bin/release/SetupProjectWix/Experiment1.msi

