name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet pacakges
      run: msbuild src\Experiment1.slnx -t:restore

    - name: Build app for release
      run: msbuild src\Experiment1.slnx -t:build -property:Configuration=Release

    - name: Upload setup artifact
      uses: actions/upload-artifact@v4
      with:
        name: setup
        path: bin/release/SetupProjectWix/Experiment1.msi

  release:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download binaries artifacts for all runtimes
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
        merge-multiple: true

    - name: Display downloaded artifacts
      run: ls -R release-artifacts

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release-artifacts/*
